name: CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: configure
        run: |
          git config --global user.email "jsuwan961205@gmail.com"
          git config --global user.name "ssuwani"

      - name: yarn install
        run: yarn

      - name: deploy
        run: npm run deploy
